// <auto-generated />
namespace Pomoce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig01));
        
        string IMigrationMetadata.Id
        {
            get { return "202006251718442_mig01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
